import asyncio
import os
import shlex
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

from prefect import flow, get_run_logger, task

CURRENT_DIR = Path(__file__).resolve().parent
SRC_DIR = CURRENT_DIR.parents[1]
if str(SRC_DIR) not in sys.path:
    sys.path.append(str(SRC_DIR))

from news.daily_news_orchestrator import (
    DEFAULT_FEEDS,
    DEFAULT_MAX_ITEMS,
    FeedItem,
    _current_news_datetime,
    _env_list,
    _news_timezone,
    fetch_feed_items,
)

DEFAULT_GEMINI_COMMAND = "gemini"
DEFAULT_GEMINI_MODEL = "gemini-2.5-flash"
DEFAULT_OBSIDIAN_ROOT = Path("obsidian")
DEFAULT_OBSIDIAN_SUBDIR = "뉴스요약"
DEFAULT_APPROVAL_MODE = "yolo"
DEFAULT_TIMEOUT_SECONDS = 180
KOREAN_WEEKDAYS = ["월", "화", "수", "목", "금", "토", "일"]


def output_frame_template(run_date: str) -> str:
    return (
        f"# 📊 {run_date} (요일) 오늘의 뉴스 요약\n\n"
        "## 🌍 국제 및 외교\n"
        "* **주요 이슈 1:** 내용\n"
        "* **주요 이슈 2:** 내용\n\n"
        "## 🇰🇷 국내 정치 및 사회\n"
        "* **주요 이슈 1:** 내용\n"
        "* **주요 이슈 2:** 내용\n\n"
        "## 📈 경제 및 금융\n"
        "* **주요 이슈 1:** 내용\n"
        "* **주요 이슈 2:** 내용\n\n"
        "## 🌦️ 날씨 및 기타\n"
        "* **날씨 또는 기타:** 내용\n"
    )


def render_gemini_prompt(items: list[FeedItem], run_date: str) -> str:
    headlines = []
    for index, item in enumerate(items, start=1):
        headlines.append(
            f"{index}. [{item.source}] {item.title}\n"
            f"   - published_at: {item.published_at or 'unknown'}\n"
            f"   - link: {item.link}"
        )

    headline_block = "\n".join(headlines)
    return (
        "뉴스요약해줘.\n\n"
        f"기준일: {run_date}\n"
        "역할: 한국어 아침 뉴스 브리핑 작성자\n"
        "입력은 RSS 헤드라인 목록뿐이다. 제공된 헤드라인 밖의 사실을 추가하지 말고, "
        "불확실하면 '헤드라인 기준 추정'이라고 명시하라.\n"
        "반드시 Markdown 본문만 출력하고 코드블록, YAML frontmatter, 메타데이터 섹션, "
        "원문 링크 목록, 체크포인트 섹션은 넣지 말라.\n"
        "아래 템플릿의 프레임만 그대로 따르고, 각 항목 내용만 채워라.\n"
        "출력 템플릿:\n"
        f"{output_frame_template(run_date)}\n"
        "규칙:\n"
        "- 각 항목은 `* **제목:** 내용` 형식으로 작성\n"
        "- 제목 1줄, 섹션 4개, 마지막 구분선과 생성 문구를 제외한 다른 블록은 만들지 말 것\n"
        "- 국제 및 외교: 2~4개 bullet\n"
        "- 국내 정치 및 사회: 2~4개 bullet\n"
        "- 경제 및 금융: 2~4개 bullet\n"
        "- 날씨 및 기타: 정확히 1개 bullet\n"
        "- 헤드라인을 묶어 자연스럽게 요약하되 과장하지 말 것\n"
        "- 날짜 제목의 요일은 한국어 한 글자 요일로 쓸 것\n\n"
        f"뉴스 목록:\n{headline_block}\n"
    )


def build_obsidian_markdown(
    run_date: str,
    summary_body: str,
) -> str:
    weekday = KOREAN_WEEKDAYS[datetime.fromisoformat(run_date).weekday()]
    normalized = summary_body.strip()
    expected_title_prefix = f"# 📊 {run_date} ({weekday}) 오늘의 뉴스 요약"

    if normalized.startswith("# "):
        lines = normalized.splitlines()
        lines[0] = expected_title_prefix
        normalized = "\n".join(lines).strip()
    else:
        normalized = f"{expected_title_prefix}\n\n{normalized}"

    generated_at = _current_news_datetime().isoformat(timespec="seconds")
    timezone_label = getattr(_news_timezone(), "key", str(_news_timezone()))
    return f"{normalized}\n\n---\n*Generated by Gemini CLI at {generated_at} ({timezone_label})*\n"


async def _fetch_news_items(feed_urls: list[str], max_items: int, logger) -> list[FeedItem]:
    collected: list[FeedItem] = []
    for feed_url in feed_urls:
        logger.info(f"Fetching RSS feed: {feed_url}")
        try:
            collected.extend(await fetch_feed_items(feed_url))
        except Exception as exc:
            logger.warning(f"Failed to fetch {feed_url}: {exc}")

    deduped: dict[str, FeedItem] = {}
    for item in collected:
        dedupe_key = item.link or item.title
        deduped.setdefault(dedupe_key, item)

    sorted_items = sorted(
        deduped.values(),
        key=lambda item: item.published_at,
        reverse=True,
    )
    limited = sorted_items[:max_items]
    logger.info(f"Collected {len(limited)} news items after deduplication")
    return limited


def run_gemini_cli(prompt: str, command: str, model: str, approval_mode: str, timeout_seconds: int) -> tuple[str, str]:
    command_parts = shlex.split(command)
    executable = command_parts[0]
    if shutil.which(executable) is None and not Path(executable).exists():
        raise RuntimeError(f"Gemini CLI executable not found: {executable}")

    cli_args = command_parts + [
        "--prompt",
        prompt,
        "--output-format",
        "text",
        "--approval-mode",
        approval_mode,
    ]
    if model:
        cli_args.extend(["--model", model])

    gemini_home = Path.home() / ".gemini"
    run_cwd = gemini_home if gemini_home.exists() else Path.cwd()

    completed = subprocess.run(
        cli_args,
        capture_output=True,
        text=True,
        timeout=timeout_seconds,
        check=False,
        cwd=run_cwd,
    )
    if completed.returncode != 0:
        raise RuntimeError(
            "Gemini CLI failed with exit code "
            f"{completed.returncode}: {completed.stderr.strip() or completed.stdout.strip()}"
        )

    output = completed.stdout.strip()
    if not output:
        raise RuntimeError("Gemini CLI returned empty output")
    return output, " ".join(cli_args)


@task(name="Fetch News Headlines For Gemini", retries=2, retry_delay_seconds=30)
async def fetch_news_task(feed_urls: list[str], max_items: int) -> list[FeedItem]:
    logger = get_run_logger()
    return await _fetch_news_items(feed_urls, max_items, logger)


@task(name="Preprocess News Prompt For Gemini")
def preprocess_news_task(items: list[FeedItem], run_date: str) -> str:
    if not items:
        raise RuntimeError("No news items were collected from RSS feeds")
    return render_gemini_prompt(items, run_date)


@task(name="Run Gemini CLI", retries=2, retry_delay_seconds=60)
def run_gemini_task(prompt: str, command: str, model: str, approval_mode: str, timeout_seconds: int) -> tuple[str, str]:
    logger = get_run_logger()
    logger.info(f"Running Gemini CLI with model={model or 'default'}")
    return run_gemini_cli(prompt, command, model, approval_mode, timeout_seconds)


@task(name="Persist Obsidian Markdown")
def persist_obsidian_task(
    markdown_text: str,
    obsidian_root: str,
    obsidian_subdir: str,
    run_date: str,
) -> str:
    logger = get_run_logger()
    root = Path(obsidian_root)
    if not root.is_absolute():
        root = Path.cwd() / root

    target_dir = root / obsidian_subdir
    target_dir.mkdir(parents=True, exist_ok=True)

    full_markdown = build_obsidian_markdown(
        run_date=run_date,
        summary_body=markdown_text,
    )

    target_path = target_dir / f"{run_date}.md"
    target_path.write_text(full_markdown, encoding="utf-8")
    logger.info(f"Saved Obsidian markdown briefing to {target_path}")
    return str(target_path)


@flow(name="Daily-News-Summary-Gemini-Flow")
async def daily_news_summary_gemini_flow(
    feed_urls: list[str] | None = None,
    obsidian_root: str | None = None,
    obsidian_subdir: str | None = None,
    max_items: int | None = None,
    gemini_command: str | None = None,
    gemini_model: str | None = None,
    approval_mode: str | None = None,
    timeout_seconds: int | None = None,
):
    logger = get_run_logger()
    resolved_feeds = feed_urls or _env_list("NEWS_RSS_FEEDS", DEFAULT_FEEDS)
    resolved_root = obsidian_root or os.getenv("OBSIDIAN_VAULT_DIR", str(DEFAULT_OBSIDIAN_ROOT))
    resolved_subdir = obsidian_subdir or os.getenv("NEWS_OBSIDIAN_SUBDIR", DEFAULT_OBSIDIAN_SUBDIR)
    resolved_max_items = max_items or int(os.getenv("NEWS_MAX_ITEMS", str(DEFAULT_MAX_ITEMS)))
    resolved_command = gemini_command or os.getenv("GEMINI_CLI_COMMAND", DEFAULT_GEMINI_COMMAND)
    resolved_model = gemini_model or os.getenv("GEMINI_MODEL", DEFAULT_GEMINI_MODEL)
    resolved_approval_mode = approval_mode or os.getenv("GEMINI_APPROVAL_MODE", DEFAULT_APPROVAL_MODE)
    resolved_timeout = timeout_seconds or int(os.getenv("GEMINI_TIMEOUT_SECONDS", str(DEFAULT_TIMEOUT_SECONDS)))
    run_date = _current_news_datetime().date().isoformat()

    logger.info(
        "Starting Gemini daily news summary flow "
        f"(feeds={len(resolved_feeds)}, obsidian_root={resolved_root}, max_items={resolved_max_items})"
    )

    items = await fetch_news_task(resolved_feeds, resolved_max_items)
    prompt = preprocess_news_task(items, run_date)
    markdown_text, _cli_command = run_gemini_task(
        prompt,
        resolved_command,
        resolved_model,
        resolved_approval_mode,
        resolved_timeout,
    )
    return persist_obsidian_task(
        markdown_text,
        resolved_root,
        resolved_subdir,
        run_date,
    )


if __name__ == "__main__":
    result = asyncio.run(daily_news_summary_gemini_flow())
    print(result)
